# Generated by Django 5.1.1 on 2024-09-08 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('lofi', 'Lofi'), ('nature', 'Nature'), ('coffee shop', 'Coffee Shop'), ('idol', 'Idol'), ('typing', 'Typing')], max_length=50)),
                ('video_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
