# Generated by Django 5.1.1 on 2024-09-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopreference',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
